/* Auto-generated by generate_manifest.py (notebook mode) */
const NTL_DATA_MANIFEST = {
  "AGO": [
    "AGO_Admin1_NTL_Annual_2012_2024.csv",
    "AGO_Admin2_NTL_Annual_2012_2024.csv",
    "AGO_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "BDI": [
    "BDI_Admin1_NTL_Annual_2012_2024.csv",
    "BDI_Admin2_NTL_Annual_2012_2024.csv",
    "BDI_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "BEN": [
    "BEN_Admin1_NTL_Annual_2012_2024.csv",
    "BEN_Admin2_NTL_Annual_2012_2024.csv",
    "BEN_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "BFA": [
    "BFA_Admin1_NTL_Annual_2012_2024.csv",
    "BFA_Admin2_NTL_Annual_2012_2024.csv",
    "BFA_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "BWA": [
    "BWA_Admin1_NTL_Annual_2012_2024.csv",
    "BWA_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "CAF": [
    "CAF_Admin1_NTL_Annual_2012_2024.csv",
    "CAF_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "CIV": [
    "CIV_Admin1_NTL_Annual_2012_2024.csv",
    "CIV_Admin2_NTL_Annual_2012_2024.csv",
    "CIV_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "CMR": [
    "CMR_Admin1_NTL_Annual_2012_2024.csv",
    "CMR_Admin2_NTL_Annual_2012_2024.csv",
    "CMR_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "COD": [
    "COD_Admin1_NTL_Annual_2012_2024.csv",
    "COD_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "COG": [
    "COG_Admin1_NTL_Annual_2012_2024.csv",
    "COG_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "COM": [
    "COM_Admin1_NTL_Annual_2012_2024.csv"
  ],
  "CPV": [
    "CPV_Admin1_NTL_Annual_2012_2024.csv"
  ],
  "DJI": [
    "DJI_Admin1_NTL_Annual_2012_2024.csv",
    "DJI_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "DZA": [
    "DZA_Admin1_NTL_Annual_2012_2024.csv",
    "DZA_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "EGY": [
    "EGY_Admin1_NTL_Annual_2012_2024.csv",
    "EGY_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "ERI": [
    "ERI_Admin1_NTL_Annual_2012_2024.csv",
    "ERI_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "ESH": [
    "ESH_Admin1_NTL_Annual_2012_2024.csv"
  ],
  "ETH": [
    "ETH_Admin1_NTL_Annual_2012_2024.csv",
    "ETH_Admin2_NTL_Annual_2012_2024.csv",
    "ETH_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "GAB": [
    "GAB_Admin1_NTL_Annual_2012_2024.csv",
    "GAB_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "GHA": [
    "GHA_Admin1_NTL_Annual_2012_2024.csv",
    "GHA_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "GIN": [
    "GIN_Admin1_NTL_Annual_2012_2024.csv",
    "GIN_Admin2_NTL_Annual_2012_2024.csv",
    "GIN_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "GMB": [
    "GMB_Admin1_NTL_Annual_2012_2024.csv",
    "GMB_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "GNB": [
    "GNB_Admin1_NTL_Annual_2012_2024.csv",
    "GNB_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "GNQ": [
    "GNQ_Admin1_NTL_Annual_2012_2024.csv",
    "GNQ_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "KEN": [
    "KEN_Admin1_NTL_Annual_2012_2024.csv",
    "KEN_Admin2_NTL_Annual_2012_2024.csv",
    "KEN_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "LBR": [
    "LBR_Admin1_NTL_Annual_2012_2024.csv",
    "LBR_Admin2_NTL_Annual_2012_2024.csv",
    "LBR_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "LBY": [
    "LBY_Admin1_NTL_Annual_2012_2024.csv"
  ],
  "LSO": [
    "LSO_Admin1_NTL_Annual_2012_2024.csv"
  ],
  "MAR": [
    "MAR_Admin1_NTL_Annual_2012_2024.csv",
    "MAR_Admin2_NTL_Annual_2012_2024.csv",
    "MAR_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "MDG": [
    "MDG_Admin1_NTL_Annual_2012_2024.csv",
    "MDG_Admin2_NTL_Annual_2012_2024.csv",
    "MDG_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "MLI": [
    "MLI_Admin1_NTL_Annual_2012_2024.csv",
    "MLI_Admin2_NTL_Annual_2012_2024.csv",
    "MLI_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "MOZ": [
    "MOZ_Admin1_NTL_Annual_2012_2024.csv",
    "MOZ_Admin2_NTL_Annual_2012_2024.csv",
    "MOZ_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "MRT": [
    "MRT_Admin1_NTL_Annual_2012_2024.csv",
    "MRT_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "MUS": [
    "MUS_Admin1_NTL_Annual_2012_2024.csv"
  ],
  "MWI": [
    "MWI_Admin1_NTL_Annual_2012_2024.csv",
    "MWI_Admin2_NTL_Annual_2012_2024.csv",
    "MWI_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "NAM": [
    "NAM_Admin1_NTL_Annual_2012_2024.csv",
    "NAM_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "NER": [
    "NER_Admin1_NTL_Annual_2012_2024.csv",
    "NER_Admin2_NTL_Annual_2012_2024.csv",
    "NER_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "NGA": [
    "NGA_Admin1_NTL_Annual_2012_2024.csv",
    "NGA_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "RWA": [
    "RWA_Admin1_NTL_Annual_2012_2024.csv",
    "RWA_Admin2_NTL_Annual_2012_2024.csv",
    "RWA_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "SDN": [
    "SDN_Admin1_NTL_Annual_2012_2024.csv",
    "SDN_Admin2_NTL_Annual_2012_2024.csv",
    "SDN_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "SEN": [
    "SEN_Admin1_NTL_Annual_2012_2024.csv",
    "SEN_Admin2_NTL_Annual_2012_2024.csv",
    "SEN_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "SLE": [
    "SLE_Admin1_NTL_Annual_2012_2024.csv",
    "SLE_Admin2_NTL_Annual_2012_2024.csv",
    "SLE_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "SOM": [
    "SOM_Admin1_NTL_Annual_2012_2024.csv",
    "SOM_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "SSD": [
    "SSD_Admin1_NTL_Annual_2012_2024.csv",
    "SSD_Admin2_NTL_Annual_2012_2024.csv",
    "SSD_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "STP": [
    "STP_Admin1_NTL_Annual_2012_2024.csv",
    "STP_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "SWZ": [
    "SWZ_Admin1_NTL_Annual_2012_2024.csv",
    "SWZ_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "SYC": [
    "SYC_Admin1_NTL_Annual_2012_2024.csv"
  ],
  "TCD": [
    "TCD_Admin1_NTL_Annual_2012_2024.csv",
    "TCD_Admin2_NTL_Annual_2012_2024.csv",
    "TCD_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "TGO": [
    "TGO_Admin1_NTL_Annual_2012_2024.csv",
    "TGO_Admin2_NTL_Annual_2012_2024.csv",
    "TGO_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "TUN": [
    "TUN_Admin1_NTL_Annual_2012_2024.csv",
    "TUN_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "TZA": [
    "TZA_Admin1_NTL_Annual_2012_2024.csv",
    "TZA_Admin2_NTL_Annual_2012_2024.csv",
    "TZA_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "UGA": [
    "UGA_Admin1_NTL_Annual_2012_2024.csv",
    "UGA_Admin2_NTL_Annual_2012_2024.csv",
    "UGA_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "ZAF": [
    "ZAF_Admin1_NTL_Annual_2012_2024.csv",
    "ZAF_Admin2_NTL_Annual_2012_2024.csv",
    "ZAF_Admin3_NTL_Annual_2012_2024.csv"
  ],
  "ZMB": [
    "ZMB_Admin1_NTL_Annual_2012_2024.csv",
    "ZMB_Admin2_NTL_Annual_2012_2024.csv"
  ],
  "ZWE": [
    "ZWE_Admin1_NTL_Annual_2012_2024.csv",
    "ZWE_Admin2_NTL_Annual_2012_2024.csv",
    "ZWE_Admin3_NTL_Annual_2012_2024.csv"
  ]
};
